
deps-run: &deps-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install --user -r doc-requirements.txt

cdf-run: &cdf-install
  name: Install CDF library
  command: |
    wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf36_3_1/linux/cdf36_3_1-dist-all.tar.gz
    tar -zxvf cdf36_3_1-dist-all.tar.gz
    cd cdf36_3-dist
    make OS=linux ENV=gnu all
    sudo make INSTALLDIR=/usr/local/cdf install
    cd ../

doc-run: &doc-build
  name: Build documentation
  command: make html
  working_directory: doc

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *deps-install
      - run: *cdf-install
      - run: *doc-build
